### ISSUE TITLE
Multisend addition

### ISSUE THREAD

**Issue by faetos** [LytixChain/lytix#13]
Since you mentioned Bulwark before i was taking a look at some of their setup and noticed multisend had the option to assign multisend to a specific address/coins versus the entire wallet. If that could be added that would be super for me unless I'm just doing something wrong. for an example I have a link: https://kb.bulwarkcrypto.com/Guides/Multisend-Setup-Guide/

**Comment by akshaynexus** [comment]
it is normally there already in pivx codebases,you sure you need to add multisend?

**Comment by faetos** [comment]
Already in as akshaynexus has pointed out. Only part that needs adding is multisend for maxnodes. Closing and re-opening a feature request for maxnodes and dev-payment to use multi-send. Ran out of time before release to add them in.
