### ISSUE TITLE
Lytix-qt fails to load on Mojave and Ubuntu 18.10

### ISSUE THREAD

**Issue by faetos** [LytixChain/lytix#6]
error log says :
ERROR: Read: Failed to open file /Users/mac/Library/Application Support/Lytix/banlist.dat
2019-01-27 15:48:19 Invalid or missing banlist.dat; recreating
2019-01-27 15:48:19 Loaded 433 addresses from peers.dat  2ms
2019-01-27 15:48:19 dnsseed thread start
2019-01-27 15:48:19 net thread start
2019-01-27 15:48:19 addcon thread start
2019-01-27 15:48:19 opencon thread start
2019-01-27 15:48:19 msghand thread start
2019-01-27 15:48:19 stakemint thread start
2019-01-27 15:48:19 ThreadStakeMinter started
2019-01-27 15:48:19 init message: Done loading
2019-01-27 15:48:20 asking peer for sporks
2019-01-27 15:48:20 ProcessMessages: advertizing address 87.138.183.93:27071
2019-01-27 15:48:20 receive version message: /Lytix Core:1.6.4/: version 71030, blocks=66061, us=87.138.183.93:63408, peer=1
2019-01-27 15:48:20 Added time data, samples 2, offset +0 (+0 minutes)
2019-01-27 15:48:20 AdvertizeLocal: advertizing address 87.138.183.93:27071
2019-01-27 15:48:20 GUI: PaymentServer::LoadRootCAs : Loaded  181  root certificates
2019-01-27 15:48:20 GUI: QObject::connect: No such slot ProposalList::computeSum() in qt/proposallist.cpp:194

**Comment by faetos** [comment]
Also fails on latest gentoo release. Binaries work on Ubuntu 18.10, but not compiling by source.

Need to see differences in compiling on  gitian trusty against 18.10 versions

**Comment by faetos** [comment]
Was able to get it working on Ubuntu 18.10 without error. There are some compile errors:

base58.cpp: In member function ‘CTxDestination CBitcoinAddress::Get() const’:
base58.cpp:289:32: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘class uint160’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
     memcpy(&id, &vchData[0], 20);
                                ^
In file included from checkpoints.h:9,
                 from chainparams.h:12,
                 from base58.h:18,
                 from base58.cpp:6:
uint256.h:320:7: note: ‘class uint160’ declared here
 class uint160 : public base_uint<160>
       ^~~~~~~
base58.cpp: In member function ‘bool CBitcoinAddress::GetKeyID(CKeyID&) const’:
base58.cpp:303:32: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘class uint160’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
     memcpy(&id, &vchData[0], 20);
                                ^
In file included from checkpoints.h:9,
                 from chainparams.h:12,
                 from base58.h:18,
                 from base58.cpp:6:
uint256.h:320:7: note: ‘class uint160’ declared here
 class uint160 : public base_uint<160>
       ^~~~~~~
  CXX      libbitcoin_common_a-chainparams.o
  CXX      libbitcoin_common_a-coins.o
  CXX      libbitcoin_common_a-compressor.o
compressor.cpp: In member function ‘bool CScriptCompressor::IsToKeyID(CKeyID&) const’:
compressor.cpp:16:37: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘class CKeyID’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
         memcpy(&hash, &script[3], 20);
                                     ^
In file included from ./script/script.h:14,
                 from primitives/transaction.h:11,
                 from compressor.h:10,
                 from compressor.cpp:7:
./pubkey.h:28:7: note: ‘class CKeyID’ declared here
 class CKeyID : public uint160
       ^~~~~~
compressor.cpp: In member function ‘bool CScriptCompressor::IsToScriptID(CScriptID&) const’:
compressor.cpp:25:37: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘class CScriptID’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
         memcpy(&hash, &script[2], 20);
                                     ^
In file included from compressor.cpp:11:
script/standard.h:21:7: note: ‘class CScriptID’ declared here
 class CScriptID : public uint160
       ^~~~~~~~~

util.cpp: In function ‘bool TryCreateDirectory(const boost::filesystem::path&)’:
util.cpp:577:33: warning: catching polymorphic type ‘class boost::filesystem::filesystem_error’ by value [-Wcatch-value=]
     } catch (boost::filesystem::filesystem_error) {

masternodeconfig.cpp: In member function ‘bool CMasternodeConfig::CMasternodeEntry::castOutputIndex(int&)’:
masternodeconfig.cpp:99:35: warning: catching polymorphic type ‘const class std::exception’ by value [-Wcatch-value=]
     } catch (const std::exception e) {


qt/forms/zpivcontroldialog.ui: Warning: The name 'verticalLayout' (QVBoxLayout) is already in use, defaulting to 'verticalLayout1'.
  GEN      qt/paymentrequest.pb.h
[libprotobuf WARNING google/protobuf/compiler/parser.cc:547] No syntax specified for the proto file: paymentrequest.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)


test/benchmark_zerocoin.cpp: In function ‘bool Testb_GenerateGroupParams()’:
test/benchmark_zerocoin.cpp:190:31: warning: catching polymorphic type ‘class std::runtime_error’ by value [-Wcatch-value=]
   } catch (std::runtime_error e) {
                               ^
test/benchmark_zerocoin.cpp: In function ‘bool Testb_ParamGen()’:
test/benchmark_zerocoin.cpp:224:25: warning: catching polymorphic type ‘class std::runtime_error’ by value [-Wcatch-value=]
  } catch (runtime_error e) {
                         ^
test/benchmark_zerocoin.cpp: In function ‘bool Testb_Accumulator()’:
test/benchmark_zerocoin.cpp:275:25: warning: catching polymorphic type ‘class std::runtime_error’ by value [-Wcatch-value=]
  } catch (runtime_error e) {
                         ^
  CXX      test/test_lytix-tutorial_zerocoin.o
  CXX      test/test_lytix-libzerocoin_tests.o
test/libzerocoin_tests.cpp: In function ‘bool Test_GenerateGroupParams()’:
test/libzerocoin_tests.cpp:162:31: warning: catching polymorphic type ‘class std::runtime_error’ by value [-Wcatch-value=]
   } catch (std::runtime_error e) {
                               ^
test/libzerocoin_tests.cpp: In function ‘bool Test_ParamGen()’:
test/libzerocoin_tests.cpp:192:25: warning: catching polymorphic type ‘class std::runtime_error’ by value [-Wcatch-value=]
  } catch (runtime_error e) {
                         ^
test/libzerocoin_tests.cpp: In function ‘bool Test_Accumulator()’:
test/libzerocoin_tests.cpp:255:25: warning: catching polymorphic type ‘class std::runtime_error’ by value [-Wcatch-value=]
  } catch (runtime_error e) {

I will work on resolving those. It did segfault on loading transactions with the "upgraded wallet." WIll test on sending a transaction and see how it does on reload

**Comment by faetos** [comment]
Dies on transactions:

2019-01-29 22:59:11 net thread start
2019-01-29 22:59:11 init message: Done loading
2019-01-29 22:59:11 addcon thread start
2019-01-29 22:59:11 opencon thread start
2019-01-29 22:59:11 msghand thread start
2019-01-29 22:59:11 dnsseed thread start
2019-01-29 22:59:11 stakemint thread start
2019-01-29 22:59:11 ThreadStakeMinter started
2019-01-29 22:59:11 LytixMiner started
2019-01-29 22:59:11 GUI: initializeResult : Initialization result:  1
2019-01-29 22:59:11 GUI: PaymentServer::LoadRootCAs : Loaded  267  root certificates
2019-01-29 22:59:11 GUI: TransactionTablePriv::refreshWallet

**Comment by faetos** [comment]
When I load the binary from the gitian build it does not fail to load on Ubuntu 18.10

**Comment by faetos** [comment]
Creating special build for Mojave. One person has said there is still an issue. Others have reported ok.

**Comment by faetos** [comment]
with qt 5.9.6 I was able to build and load the gui on ubuntu 18.10

**Comment by akshaynexus** [comment]
you might need a actual Mac to compile Mojave releases, sometimes I've seen that fix the issue

**Comment by faetos** [comment]
> you might need a actual Mac to compile Mojave releases, sometimes I've seen that fix the issue

for a backup we do that currently and produce a binary for Mojave

**Comment by faetos** [comment]
was able to update all the packages and native builds now work - closing issues
